CREATE TABLE TBL_EXP_OSET_ACTIVOXMRN
(
    PAC_ID            NUMBER
        NOT NULL ENABLE,
    ADMISION          NUMBER
        NOT NULL ENABLE,
    OSET_ID           NUMBER
        NOT NULL ENABLE,
    OSET_DESC         VARCHAR2(200 BYTE)
        NOT NULL ENABLE,
    MEDICO_USUARIO    VARCHAR2(30 BYTE)
        NOT NULL ENABLE,
    CREATED_BY        VARCHAR2(30 BYTE)
        NOT NULL ENABLE,
    CREATED_DATE      DATE DEFAULT SYSDATE,
    MODIFIED_BY       VARCHAR2(30 BYTE),
    MODIFIED_DATE     DATE,
    ESTADO            CHAR(1 BYTE),
    OBSERVACION       VARCHAR2(300 BYTE),
    ORDER_EJECUTION   NUMBER
)

COMMENT ON COLUMN TBL_EXP_OSET_ACTIVOXMRN.PAC_ID IS 'pacient MRN';
COMMENT ON COLUMN TBL_EXP_OSET_ACTIVOXMRN.ADMISION IS 'admision';
COMMENT ON COLUMN TBL_EXP_OSET_ACTIVOXMRN.OSET_ID IS 'order set id';
COMMENT ON COLUMN TBL_EXP_OSET_ACTIVOXMRN.OSET_DESC IS 'description';
COMMENT ON COLUMN TBL_EXP_OSET_ACTIVOXMRN.MEDICO_USUARIO IS 'codigo_medico quien activa';
COMMENT ON COLUMN TBL_EXP_OSET_ACTIVOXMRN.ESTADO IS '''A'' or ''I''';

--Josué 20200129
alter table TBL_EXP_OSET_ACTIVOXMRN add medico_nombre varchar(500);